name: Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Set up .NET environment
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0 # Update this to match your .NET version

    # 3. Install dependencies
    - name: Install dependencies
      run: dotnet restore

    # 4. Build the project
    - name: Build the project
      run: dotnet build --no-restore --configuration Release
